### ISSUE TITLE
1M 이상 다운로드 불가능.

### ISSUE THREAD

**Issue by hoyeong** [TurtleShip/webtoon-crawler#2]
webtoon-crawler-master/src/main/java/wcNaver/NaverToonDownloader.java

 216 라인 수정 : wtRes = Jsoup.connect(imgURL).referrer(wtURL).ignoreContentType(true).maxBodySize(5242880).method(Connection.Method.POST).execute();

**Comment by TurtleShip** [comment]
앗! 감사합니다.

오늘 저녁에 고치도록 하겠습니다 😄

**Comment by TurtleShip** [comment]
아래 commit으로 말씀하신 수정 반영하였습니다. Downloadable jar 도 업데이트 하였고, README도 업데이트 했습니다.
감사드리고, 혹시 나중에 Pull Request 만드시면 환영합니다 👍 

e216180ae922d6b435f81b9760cf10468584da5e
017179aa87496452d595436580caffad56c0ae05
0b0a7f4ed3e86a29354305abdd82c9143045e0a3

**Comment by hoyeong** [comment]
네..^^..
